//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroCard.Presentacion.WSPago {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarjeta", Namespace="http://schemas.datacontract.org/2004/07/MetroCard.Service.Dominio")]
    [System.SerializableAttribute()]
    public partial class Tarjeta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SaldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSaldo {
            get {
                return this.FechaSaldoField;
            }
            set {
                if ((this.FechaSaldoField.Equals(value) != true)) {
                    this.FechaSaldoField = value;
                    this.RaisePropertyChanged("FechaSaldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTarjeta {
            get {
                return this.IdTarjetaField;
            }
            set {
                if ((this.IdTarjetaField.Equals(value) != true)) {
                    this.IdTarjetaField = value;
                    this.RaisePropertyChanged("IdTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroTarjeta {
            get {
                return this.NroTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.NroTarjetaField, value) != true)) {
                    this.NroTarjetaField = value;
                    this.RaisePropertyChanged("NroTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TarjetaResponse", Namespace="http://schemas.datacontract.org/2004/07/MetroCard.Service.Response")]
    [System.SerializableAttribute()]
    public partial class TarjetaResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsValidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetroCard.Presentacion.WSPago.Tarjeta TarjetaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsValido {
            get {
                return this.EsValidoField;
            }
            set {
                if ((this.EsValidoField.Equals(value) != true)) {
                    this.EsValidoField = value;
                    this.RaisePropertyChanged("EsValido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetroCard.Presentacion.WSPago.Tarjeta Tarjeta {
            get {
                return this.TarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.TarjetaField, value) != true)) {
                    this.TarjetaField = value;
                    this.RaisePropertyChanged("Tarjeta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidorException", Namespace="http://schemas.datacontract.org/2004/07/MetroCard.Service.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidorException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSPago.IPagoService")]
    public interface IPagoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagoService/RecargarTarjeta", ReplyAction="http://tempuri.org/IPagoService/RecargarTarjetaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MetroCard.Presentacion.WSPago.RepetidorException), Action="http://tempuri.org/IPagoService/RecargarTarjetaRepetidorExceptionFault", Name="RepetidorException", Namespace="http://schemas.datacontract.org/2004/07/MetroCard.Service.Errores")]
        MetroCard.Presentacion.WSPago.TarjetaResponse RecargarTarjeta(MetroCard.Presentacion.WSPago.Tarjeta Tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagoService/RecargarTarjeta", ReplyAction="http://tempuri.org/IPagoService/RecargarTarjetaResponse")]
        System.Threading.Tasks.Task<MetroCard.Presentacion.WSPago.TarjetaResponse> RecargarTarjetaAsync(MetroCard.Presentacion.WSPago.Tarjeta Tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagoService/DescontarTarjeta", ReplyAction="http://tempuri.org/IPagoService/DescontarTarjetaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MetroCard.Presentacion.WSPago.RepetidorException), Action="http://tempuri.org/IPagoService/DescontarTarjetaRepetidorExceptionFault", Name="RepetidorException", Namespace="http://schemas.datacontract.org/2004/07/MetroCard.Service.Errores")]
        MetroCard.Presentacion.WSPago.TarjetaResponse DescontarTarjeta(MetroCard.Presentacion.WSPago.Tarjeta Tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagoService/DescontarTarjeta", ReplyAction="http://tempuri.org/IPagoService/DescontarTarjetaResponse")]
        System.Threading.Tasks.Task<MetroCard.Presentacion.WSPago.TarjetaResponse> DescontarTarjetaAsync(MetroCard.Presentacion.WSPago.Tarjeta Tarjeta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagoServiceChannel : MetroCard.Presentacion.WSPago.IPagoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagoServiceClient : System.ServiceModel.ClientBase<MetroCard.Presentacion.WSPago.IPagoService>, MetroCard.Presentacion.WSPago.IPagoService {
        
        public PagoServiceClient() {
        }
        
        public PagoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MetroCard.Presentacion.WSPago.TarjetaResponse RecargarTarjeta(MetroCard.Presentacion.WSPago.Tarjeta Tarjeta) {
            return base.Channel.RecargarTarjeta(Tarjeta);
        }
        
        public System.Threading.Tasks.Task<MetroCard.Presentacion.WSPago.TarjetaResponse> RecargarTarjetaAsync(MetroCard.Presentacion.WSPago.Tarjeta Tarjeta) {
            return base.Channel.RecargarTarjetaAsync(Tarjeta);
        }
        
        public MetroCard.Presentacion.WSPago.TarjetaResponse DescontarTarjeta(MetroCard.Presentacion.WSPago.Tarjeta Tarjeta) {
            return base.Channel.DescontarTarjeta(Tarjeta);
        }
        
        public System.Threading.Tasks.Task<MetroCard.Presentacion.WSPago.TarjetaResponse> DescontarTarjetaAsync(MetroCard.Presentacion.WSPago.Tarjeta Tarjeta) {
            return base.Channel.DescontarTarjetaAsync(Tarjeta);
        }
    }
}
